# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "GLM I: Logistic Regression"
author: Dr Martyn McFarquhar
copyright: "2026"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/PCHN63112-Mixed-Models/logistic-regression  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

#sphinx:
#  config:
#    html_theme: sphinx_typo3_theme

# Some failed attempts at getting live code to work!

#binder:
#  repo: "https://github.com/rocker-org/binder"
#  ref: "master" 

#launch_buttons:
#  thebe: true

#thebe:
#  use_thebe: true
#  kernel_name: ir
  #repository_url: https://github.com/rocker-org/binder
  #branch: master

#thebe:
#  use_thebe: true
#  kernel_name: "ir"
#  repository_url: https://github.com/rocker-org/binder
#  branch: master
  

